### ISSUE TITLE
Auth Failed

### ISSUE THREAD

**Issue by TheBlackDrake** [terbolous/couchpotato.provider.norbits#2]
Hi tanks for this :)

Get this error when I'm trying to use it. (the login are correct).

01-27 13:11:03INFO[hpotato.core.plugins.base] Opening url: post https://norbits.net/api2.php?action=torrents, data: with data
01-27 13:11:03ERROR[                  norbits] Error searching norbits: Auth failed

**Comment by terbolous** [comment]
Just to be clear, you are using your passkey and not your password?

To test your authentication regardless of this plugin you can do something like this assuming you have access to curl (available on most *nix clones/derivatives):

curl -i -d '{"username": "YOURUSERNAME", "passkey": "YOURPASSKEY"}' "https://norbits.net/api2.php?action=torrents"

You should obviously replace YOURUSERNAME and YOURPASSKEY with appropriate values.

If that doesn't work, there's possibly something wrong with your Norbits account

**Comment by TheBlackDrake** [comment]
aah
I did not see that it said passkey. I used the password.
Working now.. Thanks :)

**Comment by terbolous** [comment]
No worries, glad it's working :-)
