### ISSUE TITLE
error

### ISSUE THREAD

**Issue by hankiiboy** [terbolous/couchpotato.provider.norbits#4]
Hi, I cant get this error:
Result: {u'status': 3, u'message': u'Auth failed', u'data': None}

**Comment by terbolous** [comment]
Did you specify your passkey? The Auth failed is coming from Norbits, there is something wrong with the credentials specified. 

'Innloggingsmåte' at Norbits has to be set to 'Normal' as well I believe.

**Comment by hankiiboy** [comment]
Hi, i have checked with norbits and my username and passkey is right.
Innloggingsmedoden is also Normal.

Er du forresten norsk så vi kan ta det på norsk? :)

2. jan. 2017 13:44 skrev "Erik Weber" <notifications@github.com>:

Did you specify your passkey? The Auth failed is coming from Norbits, there
is something wrong with the credentials specified.

'Innloggingsmåte' at Norbits has to be set to 'Normal' as well I believe.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/terbolous/couchpotato.provider.norbits/issues/4#issuecomment-269967933>,
or mute the thread

**Comment by terbolous** [comment]
Så norsk som du får blitt. Står 'Tvunget SSL' på? Har ikke testet med det, prøv i så fall å skru det av.

**Comment by hankiiboy** [comment]
Supert!
Tvungen SSL sto på ja.
Desktiverte SSL så fungerte det veldig bra!
Takk for god support på denne!
Godt nyttår! :-)

2. jan. 2017 14:44 skrev "Erik Weber" <notifications@github.com>:

**Comment by terbolous** [comment]
Bare hyggelig. SSL er jo i grunn fint å ha, så jeg skal undersøke om jeg kan fikse det :-)
